# Import The Library

In [ ]:
import pandas as pd

**Load the Dataset and convert it into Dataframe**

In [ ]:
df = pd.read_csv('D:\AI Health Prediction\diabetes-prediction-master\data\clean_liver.csv')
df.head(10)

,Age of the patient,Gender of the patient,Total Bilirubin,Direct Bilirubin,Alkphos Alkaline Phosphotase,Sgpt Alamine Aminotransferase,Sgot Aspartate Aminotransferase,Total Protiens,ALB Albumin,A/G Ratio Albumin and Globulin Ratio,Result
0,65.0,Female,0.7,0.1,187.0,16.0,18.0,6.8,3.3,0.90,1
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
3,58.0,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
5,46.0,Male,1.8,0.7,208.0,19.0,14.0,7.6,4.4,1.30,1
6,29.0,Female,0.9,0.3,202.0,14.0,11.0,6.7,3.6,1.10,1
7,17.0,Male,0.9,0.3,202.0,22.0,19.0,7.4,4.1,1.20,2
8,55.0,Male,0.7,0.2,290.0,53.0,58.0,6.8,3.4,1.00,1
9,57.0,Male,0.6,0.1,210.0,51.0,59.0,5.9,2.7,0.80,1

**Shape of the Dataset**

In [ ]:
df.shape

(27158, 11)

**Getting the stastical summary of the Data**

In [ ]:
df.describe()

,Age of the patient,Total Bilirubin,Direct Bilirubin,Alkphos Alkaline Phosphotase,Sgpt Alamine Aminotransferase,Sgot Aspartate Aminotransferase,Total Protiens,ALB Albumin,A/G Ratio Albumin and Globulin Ratio,Result
count,27158.000000,27158.000000,27158.000000,27158.000000,27158.000000,27158.000000,27158.000000,27158.000000,27158.000000,27158.000000
mean,44.125046,3.407909,1.541630,290.142021,81.279292,112.102879,6.472605,3.124044,0.943567,1.282790
std,15.971563,6.332486,2.895084,239.595473,181.571537,283.616005,1.081477,0.792329,0.324205,0.450363
min,4.000000,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,1.000000
25%,33.000000,0.800000,0.200000,175.000000,23.000000,26.000000,5.800000,2.600000,0.700000,1.000000
50%,45.000000,1.000000,0.300000,209.000000,36.000000,42.000000,6.600000,3.100000,0.900000,1.000000
75%,55.000000,2.700000,1.300000,298.000000,62.000000,88.000000,7.200000,3.700000,1.100000,2.000000
max,90.000000,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,2.000000

In [ ]:
# Replace 2 wih 0 in the result section 
"""0 Means No Liver Disease 
   1 Means Liver Disease (Patient)
"""

df['Result'] = df['Result'].replace(2,0)
df.head(10)

,Age of the patient,Gender of the patient,Total Bilirubin,Direct Bilirubin,Alkphos Alkaline Phosphotase,Sgpt Alamine Aminotransferase,Sgot Aspartate Aminotransferase,Total Protiens,ALB Albumin,A/G Ratio Albumin and Globulin Ratio,Result
0,65.0,Female,0.7,0.1,187.0,16.0,18.0,6.8,3.3,0.90,1
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
3,58.0,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
5,46.0,Male,1.8,0.7,208.0,19.0,14.0,7.6,4.4,1.30,1
6,29.0,Female,0.9,0.3,202.0,14.0,11.0,6.7,3.6,1.10,1
7,17.0,Male,0.9,0.3,202.0,22.0,19.0,7.4,4.1,1.20,0
8,55.0,Male,0.7,0.2,290.0,53.0,58.0,6.8,3.4,1.00,1
9,57.0,Male,0.6,0.1,210.0,51.0,59.0,5.9,2.7,0.80,1

## Data Cleaning

**Checking for Duplicates**

In [ ]:
print("Shape Before Removing Duplicates: ",df.shape)

Shape Before Removing Duplicates:  (27158, 11)

In [ ]:
df = df.drop_duplicates()
print("Shape After Removing Duplicates: ",df.shape)

Shape After Removing Duplicates:  (16389, 11)

**Check For Null Values**

In [ ]:
df.isnull().sum()

Age of the patient                      0
Gender of the patient                   0
Total Bilirubin                         0
Direct Bilirubin                        0
Alkphos Alkaline Phosphotase            0
Sgpt Alamine Aminotransferase           0
Sgot Aspartate Aminotransferase         0
Total Protiens                          0
ALB Albumin                             0
A/G Ratio Albumin and Globulin Ratio    0
Result                                  0
dtype: int64

In [ ]:

print('No of missing values in Age of the patient: ', df[df['Age of the patient'] == 0].shape[0])

No of missing values in Age of the patient:  0

In [ ]:

print('No of missing values in Direct Bilirubin: ', df[df['Direct Bilirubin'] == 0].shape[0])

No of missing values in Direct Bilirubin:  0

In [ ]:

print('No of missing values in Alkphos Alkaline Phosphotase: ', df[df['Alkphos Alkaline Phosphotase'] == 0].shape[0])

No of missing values in Alkphos Alkaline Phosphotase:  0

In [ ]:

print('No of missing values in Total Protiens : ', df[df['Total Protiens'] == 0].shape[0])

No of missing values in Total Protiens :  0

In [ ]:

print('No of missing values in ALB Albumin : ', df[df['ALB Albumin'] == 0].shape[0])

No of missing values in ALB Albumin :  0

In [ ]:

print('No of missing values in A/G Ratio Albumin and Globulin Ratio: ', df[df['A/G Ratio Albumin and Globulin Ratio'] == 0].shape[0])

No of missing values in A/G Ratio Albumin and Globulin Ratio:  0

## Data Visualization